import './globals.css'
import { cx } from '../../utils'
import { Inter, Manrope } from 'next/font/google'
import Header from '../components/Header'
import Script from 'next/script'

const inter = Inter({ subsets: ['latin'], display:"swap",variable:"--font-in" })

const manrope = Manrope({ subsets: ['latin'], display:"swap", variable:"--font-mr" })


export const metadata = {
  title: 'Bytes of Insights in DataScience',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body 
      className={cx(
        inter.variable,
        manrope.variable,
        "font-mr bg-light dark:bg-dark"
        )}>

<Script id="theme-script">
  {
    `if (localStorage.getItem('theme') === 'dark' || (!('theme' in localStorage) && window.matchMedia('(prefers-color-scheme: dark)').matches)) {
      document.documentElement.classList.add('dark')
    } else {
      document.documentElement.classList.remove('dark')
    }`
  }
</Script>



        <Header />
          {children}</body>
    </html>
  )
}
